### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kieselsteini** [starwing/lua-miniz#1]
Hi there, at the moment this project is proprietary code because it has no license attached to it. Can you please fix this :)

I would like to use your code, but at the moment it's impossible to do so.

**Comment by starwing** [comment]
Okay, I will added them to README. this library has the same license with Lua itself.

**Comment by starwing** [comment]
please notice that I included sources from xlsx module and xlsxwriter module, and modify them to fit my module. So if you want to use xlsx read/write support, you may still include license of these modules.

**Comment by kieselsteini** [comment]
Thank you very much :)
